"""`dotagents plans` -- one way to write, read, update, index and move plans.

A plan is read on every executor pass and updated at every step, so the cost
that matters is how much of it has to be read and rewritten each time. This
command makes each of those a small operation: read one section, flip one box,
append one fact, move one file.

**Where**: ``<project>/.agents/plans/``. Plans belong to a project; there is no
user-store queue. ``--dir`` points at any other plans directory.

**Layout**::

    plans/
        INDEX.md                regenerated by every mutating command
        <name>.md               a live plan: draft, ready, review or executing
        <name>/<sub>.md         a sub-plan of <name>
        on-hold/<name>.md       parked
        completed/<name>.md     done; its sub-plans move with it

**File shape** -- the one in ``references/plan_template.md``; this command reads
and edits exactly these parts::

    # <Title>

    Status: draft | ready | review | executing | on-hold | done
    Executor: <family/subrole> -- <why>

    ## Progress

    - [ ] Phase 1: <name>               pending
    - [/] Phase 2: <name>               active
    - [x] Phase 3: <name> — <outcome>   done
    - [!] Phase 4: <name> — <reason>    blocked

    ## Known Facts & Context
    ## Phases
    ### Phase 1: <name>
    ## Verification
    ## Reporting

**Reading less**: ``next`` prints the head, the progress list and the one phase
to work on; ``show --section`` and ``show --phase`` print one part; ``list`` is
one line per plan.

**Writing less**: ``start``, ``check``, ``block`` and ``uncheck`` change one
progress line; ``note`` appends one fact; ``status`` sets the plan's state and
moves the file when the state says so. Each prints one line.

Every subcommand is a class nested inside :class:`Plans`: command discovery
registers each module-level command class as a top-level command, and nesting
keeps ``add`` and ``list`` from becoming ``dotagents add`` and ``dotagents list``.
"""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path
from typing import Optional

from duho import Cli, LoggingArgs

from dotagents.cli import DotAgentsArgs


def _load_model():
    """The model beside this overlay's `lib/`, by path: the command works
    whether or not that directory is on `sys.path`."""
    path = Path(__file__).resolve().parents[1] / "lib" / "_plans.py"
    spec = importlib.util.spec_from_file_location("_dotagents_plans", path)
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


_plans = _load_model()
PlansStore = _plans.PlansStore
PLANS_DIRNAME = _plans.PLANS_DIRNAME
SECTIONS = _plans.SECTIONS
LIVE = _plans.LIVE
_fail = _plans._fail


def _out(text: str) -> None:
    """Write to stdout whatever its encoding can represent."""
    try:
        sys.stdout.write(text)
    except UnicodeEncodeError:
        encoding = sys.stdout.encoding or "ascii"
        sys.stdout.write(text.encode(encoding, "replace").decode(encoding))


# --------------------------------------------------------------------------- #
# The command
# --------------------------------------------------------------------------- #


class Plans(LoggingArgs, Cli):
    """Plans for a project: write, read a part, update a step, index, move.

    Plans live in `<project>/.agents/plans/`; `--dir` on a subcommand points at
    another plans directory."""

    _parsername_ = "plans"

    class _Base(DotAgentsArgs):
        """Shared location fields (nested: not a command of its own)."""

        dir: Optional[Path] = None
        "Plans directory override (default: <project>/.agents/plans)."
        ("--dir",)

        def store(self) -> PlansStore:
            if self.dir:
                return PlansStore(Path(self.dir).expanduser())
            if getattr(self, "global_scope", False):
                raise _fail("plans belong to a project; there is no user-store plan queue")
            return PlansStore(self.resolve_scope().agents_root / PLANS_DIRNAME)

    class _Named(_Base):
        name: str = ""
        "Plan name, as `list` prints it (`<name>` or `<parent>/<sub>`)."
        ("name",)

    class Add(_Named):
        """Create a plan from the template: Status draft, placeholders to fill.

        Pass each phase with --phase to get its Progress line and its block."""

        _parsername_ = "add"

        title: str = ""
        "The plan's title."
        ("--title", "-t")

        executor: str = ""
        "The Executor line: a role from MODELS.md and why."
        ("--executor", "-e")

        phase: "list[str]" = []
        "A phase name; repeat for each phase, in order."
        ("--phase", "-p")

        def __call__(self) -> int:
            plan = self.store().add(self.name, title=self.title, executor=self.executor,
                                    phases=list(self.phase))
            _out("%s\n" % plan.path)
            return 0

    class List(_Base):
        """One line per plan: name, status, progress, title, current phase."""

        _parsername_ = "list"

        all: bool = False
        "Include on-hold and completed plans."
        ("--all", "-a")

        completed: bool = False
        "Only completed plans."
        ("--completed",)

        as_json: bool = False
        "Emit JSON."
        ("--json",)

        def __call__(self) -> int:
            store = self.store()
            plans = store.completed() if self.completed else store.all() if self.all else store.live()
            if self.as_json:
                _out(json.dumps({"dir": str(store.root),
                                 "plans": [p.as_dict() for p in plans]}, indent=2) + "\n")
                return 0
            for plan in plans:
                _out(plan.summary() + "\n")
            return 0

    class Show(_Named):
        """Print a plan, or just one part of it."""

        _parsername_ = "show"

        section: str = ""
        "One section: head, progress, facts, phases, verification, reporting."
        ("--section", "-s")

        phase: str = ""
        "One phase's block, by id."
        ("--phase", "-p")

        as_json: bool = False
        "Emit the head and the progress list as JSON."
        ("--json",)

        def __call__(self) -> int:
            plan = self.store().require(self.name)
            if self.as_json:
                _out(json.dumps(plan.as_dict(), indent=2) + "\n")
            elif self.phase:
                _out(plan.phase_text(self.phase))
            elif self.section == "head":
                _out("\n".join(plan.lines[: plan._head_end()]).rstrip() + "\n")
            elif self.section:
                if self.section not in SECTIONS:
                    raise _fail("section must be one of: head, %s" % ", ".join(SECTIONS))
                _out(plan.section_text(SECTIONS[self.section]))
            else:
                _out("\n".join(plan.lines).rstrip("\n") + "\n")
            return 0

    class Next(_Named):
        """Print what an executor needs now.

        The head, the progress list, and the one phase to work on."""

        _parsername_ = "next"

        def __call__(self) -> int:
            plan = self.store().require(self.name)
            _out("\n".join(plan.lines[: plan._head_end()]).rstrip() + "\n\n")
            _out(plan.section_text(SECTIONS["progress"]) + "\n")
            current = plan.current()
            if current is None:
                _out("Every phase is checked. Close the plan: "
                     "dotagents plans status %s done -m \"<evidence>\"\n" % plan.name)
            else:
                _out(plan.phase_text(current.id))
            return 0

    class _Mark(_Named):
        phase: str = ""
        "Phase id, as the Progress list shows it."
        ("phase",)

        message: str = ""
        "A short outcome or reason, kept on the progress line."
        ("--message", "-m")

        BOX = " "
        NEEDS_MESSAGE = False

        def __call__(self) -> int:
            store = self.store()
            plan = store.require(self.name)
            if self.NEEDS_MESSAGE and not self.message.strip():
                raise _fail("pass -m: %s" % self.NEEDS_MESSAGE)
            if plan.status not in LIVE:
                raise _fail("%s is %s; set it live first (`plans status %s executing`)"
                            % (plan.name, plan.status or "without a Status", plan.name))
            note = self.message if self.message.strip() else ("" if self.BOX == " " else None)
            item = plan.mark(self.phase, self.BOX, note)
            if self.BOX == "/" and plan.status == "ready":
                plan.set_field("Status", "executing")
            store.save(plan)
            done, total = plan.counts()
            _out("%s: %s (%d/%d done)\n" % (plan.name, item.render()[2:], done, total))
            return 0

    class Start(_Mark):
        """Mark a phase active, before the first edit. A ready plan becomes executing."""

        _parsername_ = "start"
        BOX = "/"

    class Check(_Mark):
        """Mark a phase done, with its outcome, as soon as it is."""

        _parsername_ = "check"
        BOX = "x"
        NEEDS_MESSAGE = "the outcome, in a few words"

    class Block(_Mark):
        """Mark a phase blocked, with the reason and the command that failed."""

        _parsername_ = "block"
        BOX = "!"
        NEEDS_MESSAGE = "why it is blocked"

    class Uncheck(_Mark):
        """Put a phase back to pending."""

        _parsername_ = "uncheck"
        BOX = " "

    class Note(_Named):
        """Append one fact to Known Facts & Context, when it is learned."""

        _parsername_ = "note"

        message: str = ""
        "The fact, with its evidence."
        ("--message", "-m")

        def __call__(self) -> int:
            if not self.message.strip():
                raise _fail("pass -m: the fact to record")
            store = self.store()
            plan = store.require(self.name)
            plan.append_fact(self.message)
            store.save(plan)
            _out("%s: noted\n" % plan.name)
            return 0

    class Status(_Named):
        """Show a plan's status, or set it. `done` and `on-hold` move the file.

        `done` needs every phase checked and -m with the evidence; `on-hold`
        needs -m with the reason. Any live status moves the plan back."""

        _parsername_ = "status"

        value: str = ""
        "draft, ready, review, executing, on-hold or done. Omit to show."
        ("value",)

        message: str = ""
        "Evidence for `done`; the reason for `on-hold`."
        ("--message", "-m")

        force: bool = False
        "Close a plan that still has unchecked phases."
        ("--force",)

        def __call__(self) -> int:
            store = self.store()
            if not self.value:
                _out(store.require(self.name).summary() + "\n")
                return 0
            plan = store.set_status(self.name, self.value, note=self.message, force=self.force)
            _out("%s: %s -> %s\n" % (plan.name, plan.status, plan.path))
            return 0

    class Validate(_Named):
        """Check a plan against the required shape. Exit 1 lists what is wrong."""

        _parsername_ = "validate"

        def __call__(self) -> int:
            plan = self.store().require(self.name)
            problems = plan.problems()
            for problem in problems:
                _out("%s: %s\n" % (plan.name, problem))
            if not problems:
                _out("%s: ok\n" % plan.name)
            return 1 if problems else 0

    class Index(_Base):
        """Regenerate INDEX.md from the files (after hand edits)."""

        _parsername_ = "index"

        def __call__(self) -> int:
            _out("%s\n" % self.store().write_index())
            return 0

    class PathCmd(_Base):
        """Print the plans directory."""

        _parsername_ = "path"

        def __call__(self) -> int:
            _out("%s\n" % self.store().root)
            return 0

    _subcommands_ = [Add, List, Show, Next, Start, Check, Block, Uncheck, Note,
                     Status, Validate, Index, PathCmd]
