"""`dotagents findings` -- a per-scope findings queue: add / list / show / done /
reopen / remove / index / path.

A **finding** is a problem execution discovered (not a decision, not an idea):
something the config or the code caused that cost time, recorded so triage can
fold it into a rule later instead of an agent editing config mid-task. This
command is the mechanical side of that convention -- it never triages.

**Where** (per scope, exactly like every other scope-aware command):
``<scope-root>/findings/`` where ``<scope-root>`` is ``Scope.agents_root`` --
``<project>/.agents`` by default, the user store (``~/.agents``, ``$AGENTS_HOME``)
with ``-g``. ``--dir`` overrides the whole location for a queue that lives
elsewhere (e.g. one kept at an older config's ``dotagents/findings/``).

**Layout** (the queue discipline: active at the top level, addressed ones MOVED
-- never deleted -- to ``processed/`` after a resolution is appended; a file in
``processed/`` without one is untriaged, not done)::

    <root>/findings/
        INDEX.md               regenerated by every mutating command
        <name>.md              an ACTIVE finding
        processed/<name>.md    an ADDRESSED finding, resolution appended

**File shape** mirrors an agent memory -- a short frontmatter for the index
line, the details in the body::

    ---
    name: context-inlining-missed-bare-refs
    description: bare kb/X.md references were never inlined
    status: active
    created: 2026-09-09
    ---

    <details: what happened, what it cost, evidence>

    ## Resolution (2026-09-10)        <- appended by `done`

    <the decision, evidence, or why no action was needed>

``INDEX.md`` is one line per finding, active first, then processed -- the cheap
thing to read at session start. Hand-written notes without frontmatter are
still listed (name = file stem, description = first heading or line), and gain
a frontmatter the first time the command rewrites them.

Every subcommand is a class nested inside :class:`Findings` on purpose: command
discovery collects every module-level ``Cmd`` subclass as its own top-level
command, so module-level ``Add``/``List`` classes would ALSO register as
``dotagents add`` / ``dotagents list``. Nesting keeps them off the module
namespace; duho's source introspection resolves nested qualnames, so their
flags/help still work.
"""

from __future__ import annotations

import datetime
import json
import re
import sys
from pathlib import Path
from typing import Optional

from duho import Cli, LoggingArgs

from dotagents.cli import DotAgentsArgs, _write_stdout

FINDINGS_DIRNAME = "findings"
PROCESSED_DIRNAME = "processed"
INDEX_NAME = "INDEX.md"
#: Top-level markdown files that are never findings.
_NOT_FINDINGS = {INDEX_NAME, "README.md"}
#: Frontmatter keys, in the order they are written.
_META_KEYS = ("name", "description", "status", "created", "processed")
_FRONTMATTER_RE = re.compile(r"\A---\r?\n(.*?)\r?\n---[ \t]*(?:\r?\n|\Z)", re.DOTALL)
_MAX_SLUG = 60


def slugify(text: str) -> str:
    """A finding's file name from free text: lowercase, runs of anything that is
    not ``[a-z0-9]`` collapsed to ``-``, trimmed, at most ``_MAX_SLUG`` chars."""
    slug = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    if len(slug) > _MAX_SLUG:
        slug = slug[:_MAX_SLUG].rstrip("-")
    return slug


def _today() -> str:
    return datetime.date.today().isoformat()


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def _write(path: Path, text: str) -> None:
    """LF-only, whatever the platform (files are LF-only, every repo)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)


def _read_text_arg(inline: "Optional[str]", file: "Optional[Path]") -> "Optional[str]":
    """Resolve a ``--x TEXT`` / ``--x-file PATH`` pair; ``-`` reads stdin."""
    if inline is not None:
        return inline
    if file is None:
        return None
    if str(file) == "-":
        return sys.stdin.read()
    return _read(Path(file).expanduser())


class Finding:
    """One finding file: its frontmatter (``meta``) and markdown ``body``."""

    __slots__ = ("path", "meta", "body")

    def __init__(self, path: Path, meta: "dict[str, str]", body: str):
        self.path = Path(path)
        self.meta = meta
        self.body = body

    # -- load / render --------------------------------------------------------

    @classmethod
    def load(cls, path: Path) -> "Finding":
        """Parse a finding file. A file with no frontmatter (a hand-written note)
        still loads: name = stem, description = its first ``#`` heading or first
        non-empty line, status from which directory it sits in."""
        path = Path(path)
        text = _read(path)
        meta: "dict[str, str]" = {}
        m = _FRONTMATTER_RE.match(text)
        if m:
            for line in m.group(1).splitlines():
                key, sep, value = line.partition(":")
                if sep and key.strip():
                    meta[key.strip()] = value.strip()
            body = text[m.end():]
        else:
            body = text
        meta.setdefault("name", path.stem)
        if not meta.get("description"):
            meta["description"] = cls._first_line(body)
        if not meta.get("status"):
            meta["status"] = (
                "processed" if path.parent.name == PROCESSED_DIRNAME else "active"
            )
        return cls(path, meta, body.lstrip("\r\n"))

    @staticmethod
    def _first_line(body: str) -> str:
        for line in body.splitlines():
            line = line.strip()
            if line:
                return line.lstrip("#").strip()[:120]
        return ""

    def render(self) -> str:
        lines = ["---"]
        for key in _META_KEYS:
            if self.meta.get(key):
                lines.append("%s: %s" % (key, self.meta[key]))
        for key, value in self.meta.items():
            if key not in _META_KEYS and value:
                lines.append("%s: %s" % (key, value))
        lines.append("---")
        body = self.body.rstrip("\r\n")
        return "\n".join(lines) + "\n\n" + (body + "\n" if body else "")

    def save(self) -> None:
        _write(self.path, self.render())

    # -- accessors -----------------------------------------------------------

    @property
    def name(self) -> str:
        return self.meta.get("name", self.path.stem)

    @property
    def description(self) -> str:
        return self.meta.get("description", "")

    @property
    def status(self) -> str:
        return self.meta.get("status", "active")

    @property
    def is_active(self) -> bool:
        return self.status != "processed"

    def as_dict(self) -> "dict[str, object]":
        out: "dict[str, object]" = dict(self.meta)
        out["path"] = str(self.path)
        out["body"] = self.body
        return out

    def __repr__(self) -> str:
        return "Finding(%r, %s)" % (self.name, self.status)


class FindingsStore:
    """The findings queue under one root: ``<root>/*.md`` active,
    ``<root>/processed/*.md`` addressed, ``<root>/INDEX.md`` the index."""

    def __init__(self, root: Path):
        self.root = Path(root)

    @property
    def processed_dir(self) -> Path:
        return self.root / PROCESSED_DIRNAME

    @property
    def index_path(self) -> Path:
        return self.root / INDEX_NAME

    # -- reading --------------------------------------------------------------

    @staticmethod
    def _findings_in(directory: Path) -> "list[Finding]":
        if not directory.is_dir():
            return []
        out = []
        for p in sorted(directory.glob("*.md")):
            if p.name in _NOT_FINDINGS or p.name.startswith("_"):
                continue
            out.append(Finding.load(p))
        return out

    def active(self) -> "list[Finding]":
        return self._findings_in(self.root)

    def processed(self) -> "list[Finding]":
        return self._findings_in(self.processed_dir)

    def all(self) -> "list[Finding]":
        return self.active() + self.processed()

    def get(self, name: str) -> "Optional[Finding]":
        """Look a finding up by name (or file name, or anything that slugifies to
        it), active first, then processed."""
        wanted = {name, slugify(name)}
        if name.endswith(".md"):
            wanted.add(name[:-3])
        for finding in self.all():
            if finding.name in wanted or finding.path.stem in wanted:
                return finding
        return None

    def require(self, name: str) -> Finding:
        finding = self.get(name)
        if finding is None:
            raise SystemExit("error: no finding %r under %s" % (name, self.root))
        return finding

    # -- mutation (every one regenerates the index) ---------------------------

    def add(self, description: str, *, name: "Optional[str]" = None, body: str = "") -> Finding:
        description = " ".join(description.split())
        if not description:
            raise SystemExit("error: a finding needs a one-line description")
        slug = slugify(name or description)
        if not slug:
            raise SystemExit("error: %r yields no usable file name; pass --name" % (name or description))
        path = self.root / (slug + ".md")
        if path.exists() or (self.processed_dir / (slug + ".md")).exists():
            raise SystemExit("error: finding %r already exists under %s (pass --name)" % (slug, self.root))
        meta = {
            "name": slug,
            "description": description,
            "status": "active",
            "created": _today(),
        }
        finding = Finding(path, meta, body.strip("\r\n") or description)
        finding.save()
        self.write_index()
        return finding

    def done(self, name: str, resolution: str) -> Finding:
        """Append the resolution, mark processed, MOVE to ``processed/``."""
        resolution = resolution.strip()
        if not resolution:
            raise SystemExit(
                "error: a resolution is required -- a processed finding without one "
                "is untriaged, not done (pass -r/--resolution or --resolution-file)"
            )
        finding = self.require(name)
        if not finding.is_active:
            raise SystemExit("error: finding %r is already processed (%s)" % (finding.name, finding.path))
        today = _today()
        finding.meta["status"] = "processed"
        finding.meta["processed"] = today
        finding.body = finding.body.rstrip("\r\n") + "\n\n## Resolution (%s)\n\n%s\n" % (today, resolution)
        dest = self.processed_dir / finding.path.name
        finding.save()  # rewrite in place first (frontmatter may be new)
        dest.parent.mkdir(parents=True, exist_ok=True)
        finding.path.replace(dest)
        finding.path = dest
        self.write_index()
        return finding

    def reopen(self, name: str) -> Finding:
        """Move a processed finding back to the active queue (its resolution
        history stays in the body)."""
        finding = self.require(name)
        if finding.is_active:
            raise SystemExit("error: finding %r is already active (%s)" % (finding.name, finding.path))
        finding.meta["status"] = "active"
        finding.meta.pop("processed", None)
        dest = self.root / finding.path.name
        finding.save()
        finding.path.replace(dest)
        finding.path = dest
        self.write_index()
        return finding

    def remove(self, name: str) -> Path:
        finding = self.require(name)
        path = finding.path
        path.unlink()
        self.write_index()
        return path

    # -- index ---------------------------------------------------------------

    def render_index(self) -> str:
        active = self.active()
        processed = self.processed()
        lines = [
            "# Findings",
            "",
            "One line per finding; details are in the file. Active first; an addressed",
            "finding is MOVED to `%s/` with its resolution appended (never deleted)." % PROCESSED_DIRNAME,
            "Regenerated by `dotagents findings`.",
            "",
            "## Active",
            "",
        ]
        if active:
            for f in active:
                lines.append("- [%s](%s) — %s" % (f.name, f.path.name, f.description))
        else:
            lines.append("(none)")
        lines += ["", "## Processed", ""]
        if processed:
            for f in processed:
                when = f.meta.get("processed")
                suffix = " (processed %s)" % when if when else ""
                lines.append(
                    "- [%s](%s/%s) — %s%s"
                    % (f.name, PROCESSED_DIRNAME, f.path.name, f.description, suffix)
                )
        else:
            lines.append("(none)")
        return "\n".join(lines) + "\n"

    def write_index(self) -> Path:
        _write(self.index_path, self.render_index())
        return self.index_path


# --------------------------------------------------------------------------- #
# The command
# --------------------------------------------------------------------------- #


class Findings(LoggingArgs, Cli):
    """Findings queue for a scope. Scope flags go on the subcommand: `findings list -g`.

    Default scope is the project (`<project>/.agents/findings/`); `-g` uses the
    user store, `--agents-dir` overrides it, `--dir` points at any findings
    directory -- each accepted by every subcommand (`findings add -g ...`,
    `findings done -g <name> -r ...`), not by `findings` itself."""

    _parsername_ = "findings"

    class _Base(DotAgentsArgs):
        """Shared scope + `--dir` fields (nested: not a command of its own)."""

        dir: Optional[Path] = None
        "Findings directory override (default: <scope>/findings)."
        ("--dir",)

        def store(self) -> FindingsStore:
            """The queue root: `--dir`, else `<scope-root>/findings/`.

            `resolve_scope` defaults the `-g` store through `resolve_user_store`
            (`--agents-dir`, then `$AGENTS_HOME`, then `~/.agents`), so a pinned
            store is honoured here exactly as in `env` / `context`."""
            if self.dir:
                root = Path(self.dir).expanduser()
            else:
                root = self.resolve_scope().agents_root / FINDINGS_DIRNAME
            return FindingsStore(root)

    class Add(_Base):
        """Record a new finding (one-line description; optional body with details).

        The description becomes the index line; `--body` / `--body-file` carry
        the details."""

        _parsername_ = "add"

        description: str = ""
        "One-line summary of the finding (becomes the index line)."
        ("description",)

        name: Optional[str] = None
        "File name (slug) to use instead of one derived from the description."
        ("--name", "-n")

        body: Optional[str] = None
        "Details (markdown). Default: the description."
        ("--body", "-b")

        body_file: Optional[Path] = None
        "Read the details from a file (`-` = stdin)."
        ("--body-file",)

        def __call__(self) -> int:
            body = _read_text_arg(self.body, self.body_file) or ""
            finding = self.store().add(self.description, name=self.name, body=body)
            self._logger_.info("added finding %s", finding.name)
            print(finding.path)
            return 0

    class List(_Base):
        """List findings (active by default; --all, --processed, --json).

        `--all` lists both states, `--processed` only the addressed ones,
        `--json` gives a machine-readable list."""

        _parsername_ = "list"

        all: bool = False
        "Include processed findings."
        ("--all", "-a")

        processed: bool = False
        "Only processed findings."
        ("--processed",)

        as_json: bool = False
        "Emit JSON."
        ("--json",)

        def __call__(self) -> int:
            store = self.store()
            if self.processed:
                findings = store.processed()
            elif self.all:
                findings = store.all()
            else:
                findings = store.active()
            if self.as_json:
                _write_stdout(json.dumps({
                    "dir": str(store.root),
                    "findings": [
                        {k: v for k, v in f.as_dict().items() if k != "body"}
                        for f in findings
                    ],
                }, indent=2) + "\n")
                return 0
            if not findings:
                self._logger_.info("no findings under %s", store.root)
                return 0
            show_status = self.all
            for f in findings:
                prefix = "[%s] " % f.status if show_status else ""
                _write_stdout("%s%s: %s\n" % (prefix, f.name, f.description))
            return 0

    class Show(_Base):
        """Print one finding, the whole file (--json for a structured form)."""

        _parsername_ = "show"

        name: str = ""
        "Finding name (the index/file name)."
        ("name",)

        as_json: bool = False
        "Emit JSON."
        ("--json",)

        def __call__(self) -> int:
            finding = self.store().require(self.name)
            if self.as_json:
                _write_stdout(json.dumps(finding.as_dict(), indent=2) + "\n")
            else:
                _write_stdout(finding.render())
            return 0

    class Done(_Base):
        """Mark a finding addressed: append the resolution, move it to processed/.

        The resolution is required -- a processed finding without one is
        untriaged, not done."""

        _parsername_ = "done"

        name: str = ""
        "Finding name."
        ("name",)

        resolution: Optional[str] = None
        "The decision, evidence, or why no action was needed."
        ("--resolution", "-r")

        resolution_file: Optional[Path] = None
        "Read the resolution from a file (`-` = stdin)."
        ("--resolution-file",)

        def __call__(self) -> int:
            resolution = _read_text_arg(self.resolution, self.resolution_file) or ""
            finding = self.store().done(self.name, resolution)
            self._logger_.info("processed finding %s", finding.name)
            print(finding.path)
            return 0

    class Reopen(_Base):
        """Move a processed finding back to the active queue."""

        _parsername_ = "reopen"

        name: str = ""
        "Finding name."
        ("name",)

        def __call__(self) -> int:
            finding = self.store().reopen(self.name)
            self._logger_.info("reopened finding %s", finding.name)
            print(finding.path)
            return 0

    class Remove(_Base):
        """Delete a finding recorded by mistake (prefer `done` for a real one).

        The queue discipline is move-never-delete; this is the exception for a
        finding that should never have been recorded."""

        _parsername_ = "remove"

        name: str = ""
        "Finding name."
        ("name",)

        def __call__(self) -> int:
            path = self.store().remove(self.name)
            self._logger_.info("removed %s", path)
            print(path)
            return 0

    class Index(_Base):
        """Regenerate INDEX.md from the files (after hand edits)."""

        _parsername_ = "index"

        def __call__(self) -> int:
            print(self.store().write_index())
            return 0

    class PathCmd(_Base):
        """Print the findings directory for the scope."""

        _parsername_ = "path"

        def __call__(self) -> int:
            print(self.store().root)
            return 0

    _subcommands_ = [Add, List, Show, Done, Reopen, Remove, Index, PathCmd]

    def __call__(self) -> int:
        self._logger_.info(
            "pick a findings subcommand: add, list, show, done, reopen, remove, index, path"
        )
        return 0
